name: Change PR assignee on open
on: 
  pull_request:
    types: 
      - opened

jobs:
  assign-pr-to-opener:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Assignee
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
          PR_ID: ${{ github.event.pull_request.node_id }}
          URL: ${{ github.event.pull_request.url }}

        run: |
          gh api graphql -f query='
            mutation($pull_request_id: ID!, assigneeIds: [ID!]!) {
              updatePullRequest(
                input: {
                  pullRequestId: $pull_request_id
                  assigneeIds: $assignee_ids
                  value: {
                    singleSelectOptionId: $option_id
                  }
                }
              ) {
                pullRequest {
                  id
                }
              }
            }' -f pull_request_id=$PR_ID -f assignee_ids=[$ASSIGNEE_ID]
