name: Change issue status on assign
on: 
  issues:
    types: [assigned]

jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Tavh's test project
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}