name: Change issue status on assign
on: 
  issues:
    types: 
      - assigned

jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "Test project"
          column: In Progress
          repo-token: ${{ secrets.TEST_REPO_TOKEN }}