name: Change issue status on assign
on: 
  issues:
    types: 
      - assigned

jobs:
  move-assigned-issue-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data        
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
          ORGANIZATION: tav-test-org
          PROJECT_NUMBER: 4
        run: |
          gh api graphql -f query='
            query($org: String!, $number: Int!) {
              organization(login: $org){
                projectV2(number: $number) {
                  id
                  fields(first:100) {
                    nodes {
                      ... on ProjectV2Field {
                        id
                        name
                      }
                      ... on ProjectV2SingleSelectField {
                        id
                        name
                        options {
                          id
                          name
                        }
                      }
                    }
                  }
                }
              }
            }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json

          echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
          echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
          echo 'IN_PROGRESS_OPTION_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="In Progress") |.id' project_data.json) >> $GITHUB_ENV
        
      - name: Update issue status
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_REPO_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.id }}
        run: |
          gh api graphql -f query='
            mutation($project_id: ID!, $issue_d: ID!, $status_field_id: ID!, $option_id: String!) {
              updateProjectV2ItemFieldValue(
                input: {
                  projectId: $project_id
                  itemId: $issue_id
                  fieldId: $status_field_id
                  value: { 
                    singleSelectOptionId: $option_id
                  }
                }
              ) {
                projectV2Item {
                  id
                }
              }
            }' -f project_id=$PROJECT_ID -f issue_id=$ISSUE_ID -f status_field_id=$STATUS_FIELD_ID -f option_id=$IN_PROGRESS_OPTION_ID

