name: Go

on:
  issues:
    types:
      - assigned

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Github issues automation
      uses: tavh/github-issues-automation@v1
      with:
        github-token: ${{ secrets.GH_CUSTOM_TOKEN }}
        organization: tav-test-org
        project-number: 4
        target-status: "In Progress"
        debug: true
    
